from django.urls import path
from hello import views

urlpatterns= [
    path("hello/<name>", views.hello_there, name="hello_there"),
    path("",views.home, name="home"),
    path("about/", views.about, name="about"),
    path("contact/", views.contact, name="contact"),
    path("contactsent/", views.contactsent, name="contactsent"),
    path('play/', views.play, name='play'),
    path('playselect/', views.playselect, name='playselect'),
    path('exhibits/', views.exhibits, name='exhibits'),
    path('calendar/', views.calendar, name='calendar'),
    path('progress/', views.progress, name='progress'),
    path('account/', views.account, name='account'),
    path('help/', views.help, name='help'),
    path('playselect/shallwedance/', views.shall_we_dance, name='shall_we_dance'),
    path('playselect/EgocentrismLegoActivity/', views.egocentrism_lego_activity, name='egocentrism_lego_activity'),
    path('playselect/timetodraw', views.time_to_draw,name='time_to_draw'),
    path('playselect/whoisfaster',views.who_is_faster, name='who_is_faster'),
    path('playselect/attheraces', views.at_the_races, name='at_the_races'),
    path('playselect/stopthatball', views.stop_that_ball, name='stop_that_ball'),
    path('playselect/wherewillitgo', views.where_will_it_go, name='where_will_it_go'),
    path('playselect/pilotingaboat', views.piloting_a_boat, name='piloting_a_boat'),
    path('playselect/orderup', views.order_up, name='order_up'),
    path('playselect/kaleidoscope', views.kaleidoscope, name='kaleidoscope'),
    path('playselect/twinklestartheatre', views.twinkle_star_theatre, name='twinkle_star_theatre'),
    path('playselect/eatingtherainbow', views.eating_the_rainbow, name='eating_the_rainbow'),
    path('playselect/Ahoythere', views.ahoy_there, name='ahoy_there'),
    path('playselect/sorting', views.sorting, name='sorting'),
    path('playselect/BilingualActivity', views.bilingual_activity, name='bilingual_activity'),
    path('playselect/nutrition', views.nutrition, name='nutrition'),
    path('playselect/money', views.money, name='money'),
    path('playselect/bones', views.bones, name='bones'),
    path('playselect/advancedpizzamking', views.advanced_pizza_making, name="advanced_pizza_making"),
    path('playselect/planningaparty', views.planning_a_party, name="planning_a_party"),
    path('playselect/firefighter', views.firefighter, name='firefighter'),
    path('playselect/howthemindwanders', views.how_the_mind_wanders, name='how_the_mind_wanders'),
    path('playselect/howhigh', views.how_high, name='how_high'),
    path('playselect/howstrong', views.how_strong, name='how_strong'),
    path('playselect/hiddentreasure', views.hidden_treasure, name='hidden_treasure'),
    path('playselect/sailing', views.sailing, name='sailing'),
    path('playselect/whatsdownthere', views.whats_down_there, name='whats_down_there'),
    path('playselect/surelyyourejoking', views.surely_youre_joking, name='surely_youre_joking'),
    path('playselect/letters', views.letters, name='letters'),
]