# Generated by Django 5.0.1 on 2024-04-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('activity_id', models.IntegerField(primary_key=True, serialize=False)),
                ('exhibit_id', models.IntegerField()),
                ('play_id', models.IntegerField()),
                ('act_name', models.CharField(max_length=100)),
                ('act_desc', models.TextField()),
                ('activity_extend', models.TextField(blank=True, null=True)),
                ('whats_learned', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='play',
            name='Cognitive',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='play',
            name='Communication',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='play',
            name='Physical',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='play',
            name='Sensory',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='play',
            name='Social_Emotional',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='play',
            name='play_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
