# Generated by Django 5.0.1 on 2024-04-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_activity_play_cognitive_play_communication_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='activity_id',
            new_name='activity_ID',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='act_name',
            new_name='activity_name',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='exhibit_id',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='play_id',
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_extend',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='whats_learned',
            field=models.TextField(),
        ),
    ]
